services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
    - 25565:25565
    environment:
      EULA: 'TRUE'
      TYPE: FABRIC
      VERSION: 1.21.7
      MEMORY: 1000M
      MOTD: Adalie's MC Server
      USE_AIKAR_FLAGS: 'true'
      TZ: America/Los_Angeles
      DIFFICULTY: '3'
      ENABLE_COMMAND_BLOCK: 'true'
      SIMULATION_DISTANCE: '12'
      VIEW_DISTANCE: '32'
      REGION_FILE_COMPRESSION: lz4
      SYNC_CHUNK_WRITES: 'false'
      OPS: DaCubeKing
      EXISTING_OPS_FILE: SYNCHRONIZE
      ENABLE_WHITELIST: 'true'
      WHITELIST: DaCubeKing
      EXISTING_WHITELIST_FILE: MERGE
      REMOVE_OLD_MODS: true
      REMOVE_OLD_MODS_INCLUDE: '*.jar'
      REMOVE_OLD_MODS_DEPTH: 1
      MODRINTH_PROJECTS: 'g96Z4WVZ:VLDb95oX

        5ZwdcRci:cuRqLEAA

        sGmHWmeL:LGYOH4RN

        gZ09gTMv:HRaM9kHT

        gvQqBUqZ:77EtzYFA

        uRHq6kbO:cwLGPoai

        yBW8D80W:eNZaVVBz

        eXts2L7r:wg33PHxj

        BVzZfTc1:aEVKKdXX

        LQ3K71Q1:PqIDU2GY

        n6PXGAoM:tWxry96X

        ZVzW5oNS:eTXZb5Wq

        M08ruV16:ODwC9dEb

        fALzjamp:inWDi2cf

        PtjYWJkn:v7JHUEiF

        4I1XuqiY:N0YnseYc

        Vebnzrzj:WBIpgXZQ

        Bh37bMuy:AgGRyydH

        Ha28R6CL:mccDBWqV

        8shC1gFX:DHCqyQtH

        QdG47OkI:WcDxGReS

        uXXizFIs:CtMpt7Jr

        mOgUt4GM:JY1tNj8H

        qyVF9oeo:acb0kJIr

        e0M1UDsY:1vOnuu89

        YL57xq9U:l77DAK6U

        l6YH9Als:wPYvarTa

        Eldc1g37:vG8asQVB

        fQEb0iXm:neW85eWt

        1eAoo2KR:WxYlHLu6

        AANobbMI:ND4ROcMQ

        1IjD5062:kravz06U

        EIa1eiMm:RkAlGPsT

        1u6JkXh5:3HceS8fQ

        yn9u3ypm:gdZmLCZD

        8qkXwOnk:3siYJiWG

        w7ThoJFB:Smt2Lxmo

        wnEe9KBa:fcuAO34V

        cl223EMc:bgdjh4pG

        xGdtZczs:YWXh0Bbd

        P7dR8mSH:JIZogEYa'
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_ALLOWED_VERSION_TYPE: alpha
      VANILLATWEAKS_SHARECODE: 4ouSfl
      ENABLE_ROLLING_LOGS: 'true'
    volumes:
    - ./data:/data
