services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
    - 25565:25565
    environment:
      EULA: 'TRUE'
      TYPE: FABRIC
      VERSION: 1.21.7
      MEMORY: 12500M
      MOTD: Adalie's MC Server
      USE_AIKAR_FLAGS: 'true'
      TZ: America/Los_Angeles
      DIFFICULTY: '3'
      ENABLE_COMMAND_BLOCK: 'true'
      SIMULATION_DISTANCE: '12'
      VIEW_DISTANCE: '32'
      REGION_FILE_COMPRESSION: lz4
      SYNC_CHUNK_WRITES: 'false'
      OPS: DaCubeKing
      EXISTING_OPS_FILE: SYNCHRONIZE
      ENABLE_WHITELIST: 'true'
      WHITELIST: DaCubeKing
      EXISTING_WHITELIST_FILE: MERGE
      REMOVE_OLD_MODS: true
      REMOVE_OLD_MODS_INCLUDE: '*.jar'
      REMOVE_OLD_MODS_DEPTH: 1
      MODRINTH_PROJECTS: 'PtjYWJkn:v7JHUEiF

        gZ09gTMv:HRaM9kHT

        g96Z4WVZ:VLDb95oX

        P7dR8mSH:JIZogEYa

        M08ruV16:ODwC9dEb

        fQEb0iXm:neW85eWt

        AANobbMI:ND4ROcMQ

        wnEe9KBa:fcuAO34V

        ZVzW5oNS:eTXZb5Wq

        uRHq6kbO:cwLGPoai

        l6YH9Als:wPYvarTa

        n6PXGAoM:tWxry96X

        gvQqBUqZ:77EtzYFA

        fdZkP5Bb:xKC3g1t3

        Vebnzrzj:WBIpgXZQ

        Bh37bMuy:AgGRyydH

        Ha28R6CL:mccDBWqV

        5ZwdcRci:cuRqLEAA

        1eAoo2KR:WxYlHLu6

        Eldc1g37:vG8asQVB

        jE0SjGuf:jKhQJW1O

        xGdtZczs:YWXh0Bbd

        TQTTVgYE:RXcxPvgC

        e0M1UDsY:1vOnuu89

        qyVF9oeo:acb0kJIr

        8shC1gFX:DHCqyQtH

        mOgUt4GM:JY1tNj8H

        1u6JkXh5:3HceS8fQ

        EIa1eiMm:RkAlGPsT

        1IjD5062:kravz06U

        neH5ooPP:E1od7pej

        w7ThoJFB:Smt2Lxmo

        LVN9ygNV:f3h7no4G

        4I1XuqiY:N0YnseYc

        QdG47OkI:WcDxGReS

        eXts2L7r:wg33PHxj

        yn9u3ypm:gdZmLCZD

        uXXizFIs:CtMpt7Jr

        BVzZfTc1:aEVKKdXX

        8qkXwOnk:3siYJiWG

        YL57xq9U:l77DAK6U

        yBW8D80W:eNZaVVBz

        LQ3K71Q1:PqIDU2GY

        sGmHWmeL:LGYOH4RN

        cl223EMc:bgdjh4pG

        fALzjamp:inWDi2cf

        sml2FMaA:8oiUayeD'
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_ALLOWED_VERSION_TYPE: alpha
      VANILLATWEAKS_SHARECODE: 4ouSfl
      ENABLE_ROLLING_LOGS: 'true'
    volumes:
    - ./data:/data
